# Python on Linux Web App
# Build a Python project (using Django/Flask/Bottle frameworks) and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
on:
  push:
    branches:
      - master

name: Build and deploy Python app
jobs:
 build-and-deploy:  
  runs-on: ubuntu-latest
  steps:
  # checkout the repo 
  - uses: actions/checkout@master
  # setup python
  - name: Setup Python
    uses: actions/setup-python@v1
    with:
     python-version: 3.7
  # install dependencies
  - name: python install
    working-directory: wisdompets 
    run: |
     sudo apt install python3.7-venv
     python -m venv --copies antenv
     source antenv/bin/activate
     pip install setuptools
     pip install -r requirements.txt
  # Azure login
  - uses: azure/login@v1
    with:
     creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET_9a05 }}
  - uses: azure/appservice-settings@v1
    with:
     app-name: emptyvss
     general-settings-json: '{"linuxFxVersion": "PYTHON|3.7"}' #'General configuration settings as Key Value pairs'
  # deploy web app
  - uses: azure/webapps-deploy@v2
    with:
     app-name: emptyvss
     package: wisdompets
     startup-command: gunicorn --bind=0.0.0.0 --timeout 600  wisdompets.wsgi:application
  # Azure logout
  - name: logout
    run: |
     az logout
